### PR TITLE
Fixed #27 and #18 and Increased compatibility

### LINKED ISSUE #27: BFFS currently cannot perform file operations
Considering nobody was going to use a memory-based file system, I went ahead and pulled #23 due to it also adding system calls and memory management.

If anyone wants to help with BFFS, don't hesitate.

### PR DESCRIPTION
**Pull request by melihxz**
### 📢 **PR Desc**

**Summary:** This PR addresses several critical issues with the x86_64 platform #18 and enhances the Baby's First File System (BFFS) #27 . It includes key fixes and improvements to ensure better stability and performance. 🛠️🚀

**Changes Made:**

- **Fixed Output Issues on x86_64:** Resolved problems with incorrect or garbled output on the x86_64 architecture. This includes addressing issues with data formatting and display accuracy. 🖥️✨
- **Resolved BFFS (Baby's First File System) Issues:** Corrected various bugs and inconsistencies in the BFFS. These fixes aim to improve the file system's stability and overall performance. 🗄️🔧
- **Improved Keyboard Input Handling:** Enhanced the keyboard input processing to ensure accurate character input and better handling of special keys. This includes improvements to the scancode-to-ASCII conversion and handling of multi-byte scan codes. ⌨️
- **Updated Cursor Handling and Display Logic:** Refined cursor management to ensure smooth text display and correct cursor positioning. Implemented better handling of line wrapping and screen scrolling. 🖋️📜
- **Enhanced Shell Command Execution:** Improved the shell's command execution capabilities, ensuring more reliable parsing and execution of user commands. This includes better handling of user inputs and command feedback. 🐚🔍

**Details:**

- **Output Fixes:** addressed issues where output formatting was incorrect or corrupted, adjustments were made to ensure that text is displayed properly on the screen, and scrolling and wrapping work as expected.
- **BFFS Improvements:** focused on resolving file system bugs that affected file reading, writing, and overall system stability, enhancements made to ensure the file system operates smoothly and efficiently.
- **Keyboard Input Enhancements:** updated the keyboard input handling mechanism to improve accuracy and response, special attention was given to ensure that characters are correctly interpreted and displayed.
- **Cursor and Display Updates:** optimized cursor movement and text display logic to enhance user experience, This includes fixing line wrapping issues and ensuring that text scrolling works as intended.
- **Shell Improvements:** made several updates to the shell command execution process, resulting in more robust and reliable command handling.

**Testing:** all changes have been thoroughly tested and validated to ensure they function correctly and meet performance expectations. 🎯✅

**Notes:** please review the updated files and changes for more details. this PR should significantly improve the overall system performance and usability, The Changes are `NOT TESTED`.

**Thanks for not reading** ***this!***

### CODE REVIEW

**Review by melihxz — COMMENTED** [review]
There may be some  little shit codes but most of code is alright

**Comment by Goldside543** [comment]
Looks alright, yeah, but does it compile? No.

image_2024-08-11_134957514

Fix these issues with the code, and I'll pull it.

PS: lmfao what's with adding yourself as maintainer of the whole repository alongside myself? I'm the one who gets to do that!

If you want to maintain something, ya got to pick a directory. (boot, drivers, Documentation, etc)

**Comment by Goldside543** [comment]
By the way, just made a CREDITS file. You can put yourself in there, instead.

**Review by Goldside543 — CHANGES_REQUESTED** [review]
As I said before, make those fixes, and you'll have my approval.

**Comment by melihxz** [comment]
> As I said before, make those fixes, and you'll have my approval.

Lol, sorry i was sleepy
I fixed problems, you can pull now

**Review by Goldside543 — APPROVED** [review]
Alright, so in window.c, it's `void draw_window(Window *win)`, and in window.h, it's `void draw_window(const Window *win)`. I don't know how adding `const` changes things, so I took it out for the sake of compilation.

In fs_syscalls.c, you used `print()` without including it. Add `#include "../kernel/print.h" to the file and that'll work.

Add that line and either explain why `const` is needed and add it to window.c, or remove it from window.h, and I'll merge it.

**Comment by melihxz** [comment]
> Alright, so in window.c, it's `void draw_window(Window *win)`, and in window.h, it's `void draw_window(const Window *win)`. I don't know how adding `const` changes things, so I took it out for the sake of compilation.
> 
> In fs_syscalls.c, you used `print()` without including it. Add `#include "../kernel/print.h" to the file and that'll work.
> 
> Add that line and either explain why `const` is needed and add it to window.c, or remove it from window.h, and I'll merge it.

increases security of code by don't allowing to change win x or win y, they are just readable but it dont allows to change border color x or y etc. 
If you don't wan't to make only readable you can just delete const and allow to change window things, which i recommend that

**Review by Goldside543 — APPROVED** [review]
Great, ready to merge!

**Pull request merged**
